#!/bin/sh
#
# Build optional components (eg, may depend on third-party libraries)
# -----------------------------------------------------------------------------
cd ${0%/*} || exit 1    # run from this directory
set -x

# get tecio library
./getTecIO

# build tecio
wmake libso tecio/tecsrc/ ../../tecioMake/

# build converter
wmake foamToTecplot360

# ----------------------------------------------------------------- end-of-file
