#!/bin/sh
#
# Build optional components (eg, may depend on third-party libraries)
# -----------------------------------------------------------------------------
cd ${0%/*} || exit 1    # run from this directory
set -x

# clean tecio
wclean libso tecio/tecsrc/ ../../tecioMake/

# clean converter code
wclean foamToTecplot360

# ----------------------------------------------------------------- end-of-file
